### ISSUE TITLE
Building on GNU/Linux

### ISSUE THREAD

**Issue by barf** [makigumo/PSXLoader#1]
Hello I'm new to building Hopper plugins, forgive me needing to ask this!

I built the prerequisite MIPSCPU plugin OK, but how do I build this when it is missing Makefile?

**Comment by makigumo** [comment]
Thank you for your feedback.

I added a Makefile, so this should now build fine on Linux.

Unfortunately the plugin seems to be broken, either by poor programming on my side, or some change on Hoppers side. I will look into it :/

**Comment by makigumo** [comment]
OK, I think I solved the issues.

One issue was the selection of an outdated cpu family for the MIPSCPU plugin.
Another issue is an incompatibility with clang 7.0.
So I would advise you to build the SDK and plugins with clang 6.0 or lower, or use the docker image with the precompiled SDK.
